// <auto-generated />
namespace WebApplication9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class kl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kl));
        
        string IMigrationMetadata.Id
        {
            get { return "202004132316513_kl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
